# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "🔥 Feature-rich interactive Jira command-line"
  homepage "https://github.com/anatolyD/jira-cli"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.9.0/jira_1.9.0_macOS_x86_64.tar.gz"
      sha256 "3581f5d981378b730308548d0728877c4ee8dfccc3c34ee60a1406e2b1e706d7"

      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.9.0/jira_1.9.0_macOS_arm64.tar.gz"
      sha256 "674e19fd35c9baf5d4f695a236f91cdb93ac89099914ab6a7171562a12c9ded1"

      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.9.0/jira_1.9.0_linux_x86_64.tar.gz"
      sha256 "cc86cb0afab69134bbe470fdae28094e73a8421b0c31e41a07a1e4340149a67d"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.9.0/jira_1.9.0_linux_armv6.tar.gz"
      sha256 "392c7c07cda5f2f78d75452df325b75572449513b42dfbf13f91b01d0a078fb6"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.9.0/jira_1.9.0_linux_arm64.tar.gz"
      sha256 "0ebda343f1aed2e436d81dc20a60f3108c646f56a160b9c0fef37ae75fed2719"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  head do
    url "https://github.com/anatolyD/jira-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/jira version")
    assert_includes help_text, "Version=\"#{version}\""
  end
end
