# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "🔥 Feature-rich interactive Jira command-line"
  homepage "https://github.com/anatolyD/jira-cli"
  version "1.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_x86_64.tar.gz"
      sha256 "a20a8bc30d2b3ea9869b932151adf358959f0e7f402b19488f878cd8c647b5c7"

      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.8.0/jira_1.8.0_macOS_arm64.tar.gz"
      sha256 "1d084b747d828b432f959cde96a564bc997b3e47cb4188a6284079c83d3b34f3"

      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_x86_64.tar.gz"
      sha256 "3a0576cacd2830468237485b5567bd5772ad9b1e54128d1a146301a8f6cd22fd"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_armv6.tar.gz"
      sha256 "edc06d29fe881c1cf070fcdfac825b8e4b05e428ed33afc479b5a9b0dca759f8"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anatolyD/jira-cli/releases/download/v1.8.0/jira_1.8.0_linux_arm64.tar.gz"
      sha256 "87e0fc66e7190a0276b7cc3638a21b32d5673598bdc98a401b14383826c2e0b0"
      define_method(:install) do
        if build.head?
          system "make", "install"
          bin.install ENV["GOPATH"] + "/bin/jira"
        else
          bin.install File.exist?("bin/jira") ? "bin/jira" : "jira"
        end
        generate_completions_from_executable(bin/"jira", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  head do
    url "https://github.com/anatolyD/jira-cli.git", branch: "main"
    depends_on "go"
  end

  test do
    help_text = shell_output("#{bin}/jira version")
    assert_includes help_text, "Version=\"#{version}\""
  end
end
